[project]
name = "heflex"
version = "0.1.0"
description = "A micro framework for writing beautiful HTMX applications"
readme = "README.md"
authors = [
    { name = "Michael Delago", email = "michaeldelago98@gmail.com" }
]
license = { text = "GPL-3.0-or-later" }
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "python-multipart>=0.0.32",
]

[build-system]
requires = ["uv_build>=0.11.5,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "httpx2>=2.12.0",
    "pytest>=9.1.1",
    "pytest-playwright-asyncio>=0.9.0",
    "pytest-timeout>=2.4.0",
    "uvicorn>=0.52.4",
]

[tool.pytest]
timeout = "60"
asyncio_mode = "auto"
asyncio_default_test_loop_scope = "session"

[tool.pytest_asyncio]
mode = "auto"
default_test_loop_scope = "session"
